# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd1eaf4d2983babfcdda01d7d0ac39d383268819507afae57af2f948413a56e547991733a8c7ecd51e93b0966d9702f34643c858edeaea86292472e5862efa52

test:
  secret_key_base: 09aad3da56135f8b8fbda6b8243cd1a2b896f7156515645ce2cd675c9979b98ff0851218b526c77fd1f4f40748aa45098acfce852bf23c1df65d30b3c2be1ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
